# Generated by Django 5.1 on 2024-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('event', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('camera', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
