# Generated by Django 5.1 on 2024-10-03 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotlist',
            name='camera',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='snapshotlist',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='snapshotlist',
            name='event',
            field=models.CharField(default='Chụp hình', max_length=50),
        ),
        migrations.AlterModelTable(
            name='snapshotlist',
            table='app_snapshotlist',
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('rtsp', 'RTSP')], default='rtsp', max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('stream_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camera',
            },
        ),
    ]
